# Generated by Django 2.1.4 on 2019-02-14 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='full name')),
                ('alternative_name', models.CharField(blank=True, default='', max_length=255, verbose_name='alternative name')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('life_path_number', models.PositiveSmallIntegerField(blank=True, default=0, help_text='From birthday')),
                ('destiny_number', models.PositiveSmallIntegerField(blank=True, default=0, help_text='From Full Name')),
                ('alternative_destiny_number', models.PositiveSmallIntegerField(blank=True, default=0, help_text='From Alternative Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerology_chart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
