# Generated by Django 2.1.4 on 2019-02-14 00:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('numerology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerologychart',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
