# Generated by Django 2.1.4 on 2019-02-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0002_numerologychart_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerologychart',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
