# Generated by Django 2.1.4 on 2019-02-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrochart', to='charts.Chart')),
            ],
        ),
    ]
