# Generated by Django 2.1.4 on 2019-02-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrochart',
            name='sun',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
