# Generated by Django 2.1.4 on 2019-02-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_astrochart_sun'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrochart',
            name='jupiter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='mars',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='mercury',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='moon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='neptune',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='pluto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='saturn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='uranus',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astrochart',
            name='venus',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
