# Generated by Django 2.1.4 on 2019-04-07 15:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_astrochart_sinastry_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrochart',
            name='sinastry_points',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
