# Generated by Django 2.1.4 on 2019-03-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('circuit_group', models.CharField(max_length=30)),
                ('circuit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RaveChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.ManyToManyField(to='hds.Channel')),
                ('chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ravechart', to='charts.Chart')),
                ('gates', models.ManyToManyField(to='hds.Gate')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='gate1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate1', to='hds.Gate'),
        ),
        migrations.AddField(
            model_name='channel',
            name='gate2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate2', to='hds.Gate'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('gate1', 'gate2')},
        ),
    ]
