# Generated by Django 2.1.4 on 2019-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ravechart',
            name='ajna',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='g',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='head',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='heart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='root',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='sacral',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='solar_plexus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='throat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ravechart',
            name='centers',
            field=models.ManyToManyField(to='hds.Center'),
        ),
    ]
