# Generated by Django 2.1.4 on 2019-06-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0003_auto_20190617_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ravechart',
            old_name='centers',
            new_name='defined_centers',
        ),
    ]
