# Generated by Django 2.1.4 on 2019-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0005_auto_20190617_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
