# Generated by Django 2.1.4 on 2019-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0006_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
