# Generated by Django 2.1.4 on 2019-02-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0007_auto_20190216_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravechart',
            name='chart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ravechart', to='charts.Chart'),
        ),
    ]
