# Generated by Django 2.1.4 on 2019-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0008_auto_20190216_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate1', models.PositiveSmallIntegerField()),
                ('gate2', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('circuit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hexagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
