# Generated by Django 2.1.4 on 2019-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0010_auto_20190225_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('gate1', 'gate2')},
        ),
    ]
