# Generated by Django 2.1.4 on 2019-02-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0011_auto_20190225_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='gate1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate1', to='hds.Gate'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='gate2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate2', to='hds.Gate'),
        ),
    ]
