# Generated by Django 2.1.4 on 2019-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0012_auto_20190225_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='circuit_group',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
