# Generated by Django 2.1.4 on 2019-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0013_channel_circuit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravechart',
            name='gates',
            field=models.ManyToManyField(to='hds.Gate'),
        ),
    ]
