# Generated by Django 2.1.4 on 2019-02-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hds', '0014_ravechart_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravechart',
            name='channels',
            field=models.ManyToManyField(to='hds.Channel'),
        ),
    ]
