# Generated by Django 2.1.4 on 2019-02-26 22:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
