# Generated by Django 2.1.4 on 2019-06-17 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL),
        ),
    ]
