# Generated by Django 2.1.4 on 2019-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('source', models.URLField(blank=True, default='')),
            ],
        ),
    ]
